// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UrbanZoo.Models;

namespace UrbanZoo_API.Migrations
{
    [DbContext(typeof(UrbanZooContext))]
    [Migration("20220824202409_Reseeded")]
    partial class Reseeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("UrbanZoo.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lng")
                        .HasColumnType("double");

                    b.Property<string>("State")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Zipcode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(3300),
                            Description = "Owners welcome public feeding",
                            Lat = 45.471901500000001,
                            Lng = -122.6145719,
                            State = "OR",
                            StreetAddress = "SE 47th & SE rural",
                            Title = "Chicken Coup",
                            UserId = 4,
                            Zipcode = "97211"
                        },
                        new
                        {
                            FeatureId = 2,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8260),
                            Description = "Owners welcome public feeding",
                            Lat = 45.477027900000003,
                            Lng = -122.6174991,
                            State = "OR",
                            StreetAddress = "SE 44th & SE Tolman",
                            Title = "Chicken Coup",
                            UserId = 3,
                            Zipcode = "98682"
                        },
                        new
                        {
                            FeatureId = 3,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8280),
                            Description = "Can't feed the chickens",
                            Lat = 45.482752900000001,
                            Lng = 122.6164548,
                            State = "OR",
                            StreetAddress = "SE 45th Ave & SE Harold St",
                            Title = "Chicken Coup",
                            UserId = 3,
                            Zipcode = "97266"
                        },
                        new
                        {
                            FeatureId = 4,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8280),
                            Description = "Owners welcome public feeding",
                            Lat = 45.486022800000001,
                            Lng = -122.6154899,
                            State = "OR",
                            StreetAddress = "5119 SE 46th Ave",
                            Title = "Chicken Coup",
                            UserId = 2,
                            Zipcode = "98660"
                        },
                        new
                        {
                            FeatureId = 5,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8290),
                            Description = "Owners welcome public feeding",
                            Lat = 45.4846498,
                            Lng = -122.602384,
                            State = "OR",
                            StreetAddress = "5980 SE Steele St",
                            Title = "Chicken Coup",
                            UserId = 1,
                            Zipcode = "97211"
                        },
                        new
                        {
                            FeatureId = 6,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8290),
                            Description = "Owners welcome public feeding",
                            Lat = 45.487687899999997,
                            Lng = -122.6109854,
                            State = "OR",
                            StreetAddress = "4816 SE 50th Ave",
                            Title = "Chickens and Ducks",
                            UserId = 4,
                            Zipcode = "98685"
                        },
                        new
                        {
                            FeatureId = 7,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8290),
                            Description = "Behind chain linked fence",
                            Lat = 45.4895937,
                            Lng = -122.5959313,
                            State = "OR",
                            StreetAddress = "4536 SE 65th Ave",
                            Title = "Goat and Pig",
                            UserId = 1,
                            Zipcode = "97225"
                        },
                        new
                        {
                            FeatureId = 8,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8300),
                            Description = "Bring minifigs to trade. On telephone poll near address listed https://www.instagram.com/portlandminifigs/?hl=en",
                            Lat = 45.491505199999999,
                            Lng = -122.6190095,
                            State = "OR",
                            StreetAddress = "SE 42nd Ave & SE Cora St",
                            Title = "PDX Lego MiniFig Exchange",
                            UserId = 5,
                            Zipcode = "97068"
                        },
                        new
                        {
                            FeatureId = 9,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8300),
                            Description = "Back alley path with large branches to climb on",
                            Lat = 45.604418240000001,
                            Lng = -122.8296801,
                            State = "OR",
                            StreetAddress = "4700 SE 50th Ave",
                            Title = "Secret passage way",
                            UserId = 6,
                            Zipcode = "97231"
                        },
                        new
                        {
                            FeatureId = 10,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8310),
                            Description = "Rose bushes growing over sidewalk. Smells good in summer",
                            Lat = 45.484494099999999,
                            Lng = -122.5972208,
                            State = "OR",
                            StreetAddress = "6417 SE Steele St",
                            Title = "Rose tunnel ",
                            UserId = 2,
                            Zipcode = "97218"
                        },
                        new
                        {
                            FeatureId = 11,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8310),
                            Description = "Arborvitae 'tunnel' over sidewalk with toys inside",
                            Lat = 45.486687199999999,
                            Lng = -122.6147603,
                            State = "OR",
                            StreetAddress = "4601 SE Raymond St",
                            Title = "Fairy tunnel ",
                            UserId = 2,
                            Zipcode = "97218"
                        },
                        new
                        {
                            FeatureId = 12,
                            Availability = true,
                            City = "Portland",
                            CreatedDate = new DateTime(2022, 8, 24, 13, 24, 8, 746, DateTimeKind.Local).AddTicks(8320),
                            Description = "Diorama featuring dinosaurs and friends. https://www.instagram.com/pdxdinorama/?hl=en",
                            Lat = 45.516819699999999,
                            Lng = -122.58544670000001,
                            State = "OR",
                            StreetAddress = "SE 78th Ave & SE Morrison St",
                            Title = "PDX Diorama",
                            UserId = 6,
                            Zipcode = "97218"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
